[package]
name = "analytics_storage"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "mybin"
path = "src/bin/test.rs"

[dependencies]
anyhow = "1.0.91"
chrono = "0.4.38"
ms-converter = "1.4.0"
serde = "1.0.214"
serde_json = "1.0.132"
