[package]
name = "rustorama"
version = "0.1.0"
edition = "2021"

[dependencies]
config = { version = "0.14.0", features = ["json5"] }

anyhow = "1.0.91"
thiserror = "2"

tokio = { version = "1", features = ["full"] }

serde = { version = "1.0.214", features = ["derive"] }
serde_json = "1.0.132"

bincode = "1.3.3"

itertools = "0.13.0"
rayon = "1.10.0"


dashmap = { version = "6.1.0", features = ["rayon"] }
csv = "1.3.0"

ptrie = { git = "https://github.com/oramasearch/ptrie.git", branch = "feat/expose-find-postfixes-with-current" }

regex = "1.11.1"

include_dir = "0.7.4"
lazy_static = "1.5.0"
once_cell = "1.20.2"

rust-stemmers = "1.2.0"
text-splitter = { version = "0.18.1", features = ["tiktoken-rs", "markdown", "code"] }
tiktoken-rs = "0.6.0"
tree-sitter = "0.24.3"
tree-sitter-html = "0.23.0"
tree-sitter-javascript = "0.23.0"
tree-sitter-language = "0.1.2"
tree-sitter-typescript = "0.23.0"

fst = "0.4.7"
rand = "0.8.5"

cuid = "1.3.3"
ordered-float = "4.4.0"
num-traits = "0.2"

# Webserver
axum = "0.7.6"
axum-macros = "0.4.2"
tower-http = { version = "0.6.1", features = ["trace", "cors"] }
http = "1.1.0"

[build-dependencies]
cc="*"

[dev-dependencies]
futures = "0.3.31"
hurl = "5.0.1"
hurl_core = "5.0.1"
tempdir = "0.3.7"
pretty_assertions = "1.4.1"
criterion = "0.5.1"
http-body-util = "0.1.2"
mime = "0.3.17"
tower = { version = "0.5.1", features = ["util"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }



[[bin]]
name = "rustorama"
path = "src/bin/rustorama.rs"

# [workspace]
# resolver = "2"
# members = [
#     "string_index",
#     "nlp",
#     "web_server",
#     "collection_manager",
#     "storage",
#     "document_storage",
#     "types",
#     "rustorama",
#     "embeddings",
#     "tanstack_example",
#     "code_parser",
#     "vector_index",
#     "code_index",
#     "utils",
#     "llm",
#     "number_index",
#     "bool_index",
# ]
