[workspace]
resolver = "2"
members = [
    "string_index",
    "nlp",
    "content_expander",
    "web_server",
    "collection_manager",
    "storage",
    "document_storage",
    "types",
    "rustorama",
    "embeddings",
    "tanstack_example",
    "code_parser",
    "vector_index",
]
