[package]
name = "rustorama"
version = "0.1.0"
edition = "2021"

[dependencies]
config = { version = "0.14.0", features = ["json5"] }

anyhow = "1"
thiserror = "2"

smallvec = { version = "1.6.1", features = ["serde"] }

tokio = { version = "1", features = ["rt", "rt-multi-thread", "full", "sync"] }

serde = { version = "1.0.214", features = ["derive"] }
serde_json = "1.0.132"

bincode = "1.3.3"

rayon = "1.10.0"
prost = "0.13.4"
tonic = "0.12.3"

dashmap = { version = "6.1.0", features = ["rayon"] }
csv = "1.3.0"

ptrie = { git = "https://github.com/oramasearch/ptrie.git", branch = "feat/expose-find-postfixes-with-current" }

regex = "1.11.1"

invocation-counter = "0.1.0"


rust-stemmers = "1.2.0"
text-splitter = { version = "0.19", features = ["tiktoken-rs", "markdown", "code"] }
tiktoken-rs = "0.6.0"
tree-sitter = "0.24.3"
tree-sitter-html = "0.23.0"
tree-sitter-javascript = "0.23.0"
tree-sitter-typescript = "0.23.0"

async-trait = "0.1.83"


fst = "0.4.7"
rand = "0.8.5"

ordered-float = "4"
num-traits = "0.2"

futures = "0.3.31"

# Webserver
axum = "0.7.6"
tower-http = { version = "0.6.1", features = ["trace", "cors"] }
http = "1.2.0"
axum-openapi3 = { version = "0.1.0", features = ["derive"] }

# Embeddings
hora = { version = "0.1.1" }
fastembed = { version = "4.3.0", features = ["ort-download-binaries"] }
strum = { version = "0.26", features = ["derive"] }
strum_macros = "0.26.4"
ndarray = "=0.15.6"
reductive = "0.9.0"
rand_chacha = "0.3.1"
reqwest = { version = "0.12.9", features = ["blocking", "json"] }
quick-js = "0.4.1"

# Tracing
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
duration-string = "0.4.0"
deno_core = "0.325.0"
serde_v8 = "0.234.0"

# prometheus
metrics-exporter-prometheus = "0.16.0"
metrics = "0.24.1"
metrics-util = "0.18.0"
assert_approx_eq = "1.1.0"

tempdir = { version ="0.3.7", optional = true }
memmap = "0.7.0"

[build-dependencies]
cc="1"
tonic-build = "0.12.3"

[dev-dependencies]
hurl = "6.0.0"
hurl_core = "6.0.0"
pretty_assertions = "1.4.1"
criterion = { version = "0.5.1", features = ["async_tokio"] }
http-body-util = "0.1.2"
mime = "0.3.17"
tower = { version = "0.5.1", features = ["util"] }
rand = "0.8.5"

[[bin]]
name = "rustorama"
path = "src/bin/rustorama.rs"

[[bin]]
name = "insert_documents"
path = "src/bin/insert_documents.rs"

##### BIN FOR TEST #####
#[[bin]]
#name = "vector_index_test"
#path = "src/bin/vector_index_test.rs"
[[bin]]
name = "embeddings"
path = "src/bin/embeddings/embeddings.rs"
#[[bin]]
#name = "pq_bench"
#path = "src/bin/embeddings/pq_bench.rs"
#[[bin]]
#name = "pq"
#path = "src/bin/embeddings/pq.rs"
#[[bin]]
#name = "selector"
#path = "src/bin/embeddings/selector.rs"
[[bin]]
name = "deno"
path = "src/bin/js/deno.rs"

[[bench]]
name = "phrase_match"
harness = false

[features]
default = ["benchmarking"]
benchmarking = [ "tempdir" ]

[workspace]
members = [
    
]

# [workspace]
# resolver = "2"
# members = [
#     "string_index",
#     "nlp",
#     "web_server",
#     "collection_manager",
#     "storage",
#     "document_storage",
#     "types",
#     "rustorama",
#     "embeddings",
#     "tanstack_example",
#     "code_parser",
#     "vector_index",
#     "code_index",
#     "utils",
#     "llm",
#     "number_index",
#     "bool_index",
# ]
