[package]
name = "embeddings"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.92"
fastembed = { version = "4.1.0", features = ["ort-download-binaries"] }
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1"
strum = { version = "0.26", features = ["derive"] }
tokio = { version = "1.41", features = ["rt", "rt-multi-thread"] }
rayon = "1.8"