[package]
name = "document_storage"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
bincode = "1.3.3"
serde_json = "1.0.132"
storage = { path = "../storage" }
types = { path = "../types" }
