[package]
name = "web_server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
anyhow = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.132"

[[bin]]
name = "test"
path = "src/bin/main.rs"
