grpc_port: 50051
host: "0.0.0.0"
total_threads: 12

embeddings:
  default_model_group: "en"
  dynamically_load_models: false
  execution_providers: 
    - "CPUExecutionProvider"
  total_threads: 8

LLMs:
  content_expansion:
    id: "microsoft/Phi-3.5-mini-instruct"
    tensor_parallel_size: 1
    sampling_params:
      temperature: 0.2
      top_p: 0.95
      max_tokens: 512

  vision:
    id: "microsoft/Phi-3.5-vision-instruct"
    tensor_parallel_size: 1
    sampling_params:
      temperature: 0.2
      top_p: 0.95
      max_tokens: 512

  google_query_translator:
    id: "microsoft/Phi-3.5-mini-instruct"
    tensor_parallel_size: 1
    sampling_params:
      temperature: 0.2
      top_p: 0.95
      max_tokens: 20