grpc_port: 50051
host: "0.0.0.0"
total_threads: 12

embeddings:
  default_model_group: "en"
  dynamically_load_models: false
  execution_providers: 
    - "CPUExecutionProvider"
  total_threads: 8

LLMs:
  content_expansion:
    id: "Qwen/Qwen2.5-3B-Instruct"
    tensor_parallel_size: 1
    use_cpu: true
    sampling_params:
      temperature: 0.2
      top_p: 0.95
      max_tokens: 256

  google_query_translator:
    id: "Qwen/Qwen2.5-3B-Instruct"
    tensor_parallel_size: 1
    use_cpu: true
    sampling_params:
      temperature: 0.2
      top_p: 0.95
      max_tokens: 20

  answer:
    id: "Qwen/Qwen2.5-3B-Instruct"
    tensor_parallel_size: 1
    use_cpu: true
    sampling_params:
      temperature: 0.0
      top_p: 0.95
      max_tokens: 2048