name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: apt-get update
      run: sudo apt-get update
    - name: apt-get install
      run: |
        sudo apt-get install -y libssl3 pkg-config libssl-dev g++ build-essential ca-certificates
        sudo apt-get install -y nvidia-cuda-toolkit libomp-dev gobjc*aarch64*gnu
    - name: Find cc1obj
      run: |
        gcc --version
        g++ --version
        which g++
        sudo ls -lag /usr/
        sudo ls -lag /usr/libexec/
        sudo find /usr/libexec -name "cc1plus"

    - name: Set up cargo cache
      uses: actions/cache@v3
      continue-on-error: false
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/            
        key: cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: cargo-
    - name: Install target
      run: rustup target add x86_64-unknown-linux-gnu
    - name: Build
      run: |
        RUSTFLAGS="-C target-feature=+fp16" cargo build --verbose --release --target x86_64-unknown-linux-gnu
