name: Rust

on:
  push:
    branches: [ "main", "fix-ci" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: apt-get update
      run: sudo apt-get update
    - name: apt-get install
      run: sudo apt-get install -y libssl3 pkg-config libssl-dev g++ build-essential ca-certificates gobjc++-mingw-w64
    - name: Set up cargo cache
      uses: actions/cache@v3
      continue-on-error: false
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/            
        key: cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: cargo-
    - name: Install target
      run: rustup target add x86_64-unknown-linux-gnu
    - name: Build
      run: cargo build --verbose
    - name: Lint
      run: |
        cargo fmt --all -- --check
        cargo clippy -- -D warnings 
    - name: Run tests
      run: cargo test --verbose
    - name: Build release
      run: cargo build --target x86_64-unknown-linux-gnu --release -p rustorama
